### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by mschinis** [checkout/checkout-event-logger-ios-framework#14]
Hello,

I'm trying to use the `frames-ios` checkout sdk in MacOS, but this dependency of frames-ios doesn't support macOS in `Package.swift`. Can it be updated to support it?

**Comment by okhan-okbay-cko** [comment]
Hi, sorry there has been ages since you asked this. If you still need this, can you please elaborate on the use case so we can have an internal discussion about it?

**Comment by okhan-okbay-cko** [comment]
Closing this stale issue. Feel free to re-open or open a new one ✌️
